name: LiteSignIn
version: 1.3.3
main: studio.trc.bukkit.litesignin.Main
author: TRCRedstoner
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
    signin:
        description: Main commands of LiteSignIn
        aliases: [litesignin]